package chongci.myapplication.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import chongci.myapplication.Bean.GreenDaoBean;
import chongci.myapplication.view.fragment.ChinaFragment.ChangeBean;

import chongci.myapplication.dao.GreenDaoBeanDao;
import chongci.myapplication.dao.ChangeBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig greenDaoBeanDaoConfig;
    private final DaoConfig changeBeanDaoConfig;

    private final GreenDaoBeanDao greenDaoBeanDao;
    private final ChangeBeanDao changeBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        greenDaoBeanDaoConfig = daoConfigMap.get(GreenDaoBeanDao.class).clone();
        greenDaoBeanDaoConfig.initIdentityScope(type);

        changeBeanDaoConfig = daoConfigMap.get(ChangeBeanDao.class).clone();
        changeBeanDaoConfig.initIdentityScope(type);

        greenDaoBeanDao = new GreenDaoBeanDao(greenDaoBeanDaoConfig, this);
        changeBeanDao = new ChangeBeanDao(changeBeanDaoConfig, this);

        registerDao(GreenDaoBean.class, greenDaoBeanDao);
        registerDao(ChangeBean.class, changeBeanDao);
    }
    
    public void clear() {
        greenDaoBeanDaoConfig.clearIdentityScope();
        changeBeanDaoConfig.clearIdentityScope();
    }

    public GreenDaoBeanDao getGreenDaoBeanDao() {
        return greenDaoBeanDao;
    }

    public ChangeBeanDao getChangeBeanDao() {
        return changeBeanDao;
    }

}
